# $Id: Makefile,v 1.1.1.1 2001/10/15 20:44:59 mrbrown Exp $
# Makefile for Maple Bus drivers

O_TARGET	:= maplebus.o

export-objs	:= maple.o

obj-y	:=
obj-m	:=
obj-n	:=
obj-	:=

obj-$(CONFIG_MAPLE)		+= maple.o

include $(TOPDIR)/Rules.make
